
language: cpp

sudo: required

services:
    - docker

notifications:
    email: false

branches:
    only:
        - master

before_install:
    - docker pull dennisss/tansa-dev

script:
    - docker run --rm -v `pwd`:`pwd`:rw -w=`pwd` -it dennisss/tansa-dev /bin/bash -c "make test"
